### ISSUE TITLE
[BUG] - Can't rename "NomDeVotreJeu" folder

### ISSUE THREAD

**Issue by Catoune** [Narudgi/RubikarioWare#1]
**Description du bug**
Lorsque j'essaye de renommer le dossier "**NomDeVotreJeu**", une fenêtre d'erreur apparaît et indique : _Moving Assets/Micro/NomDeVotreJeu_ to _Assets/Micro/TestName_ : **Accès refusé**

**Reproduction du bug**
Étapes pour reproduire le problème:
1. Renommer le dossier
2. Rentrez du texte
3. Appuyez sur "Entrée"
4. Constate l'erreur

**Comportment attendu**
Bah qu'il y'est pas d'erreur wesh

**Divers**
Lorsqu'on copie le dossier, on peut renommer sa copie.

**Comment by MightyPietro** [comment]
Nous vous conseillons de copier / coller le dossier et de tout faire dans celui-ci.
Nous n'avons pas vraiment la main mise sur le problème.
