### ISSUE TITLE
[BUG] - Missing MiddleGround Sorting Layer

### ISSUE THREAD

**Issue by Catoune** [Narudgi/RubikarioWare#2]
**Description du bug**
Le document Macro présente un sorting layer nommé "**Middledround**" sauf qu'il n'est pas présent dans le projet.

**Reproduction du bug**
- Component<SpriteRenderer>
- Sorting Layer

**Comment by MightyPietro** [comment]
" Sorting Layer " est un composant qui se trouve dans le composant " Sprite Renderer ". Il y a 3 " Sorting Layer " : 

- BackGround
- Default ( = MiddleGround ) 
- ForeGround
