### ISSUE TITLE
[BUG] - Ajout de Sprites

### ISSUE THREAD

**Issue by Linkazer** [Narudgi/RubikarioWare#3]
**Description du bug**
Lorsqu’on ajoute un sprite dans le dossier et qu'on le glisse dans la scène, il devient méticuleusement petit (une image en 1920/1080 qui passe en 3pixel par 2pixel

**Reproduction du bug**
Étapes pour reproduire le problème:
1. Ajoute un nouveau sprite dans le dossier de ton micro-jeu
2. Glisse le ensuite dans ta scène
3. Zoom jusqu'à l'infini pour apercevoir le dit sprite en format minuscule

**Comportment attendu**
Le sprite en question apparaît en minuscule sur l'écran (voir n'apparaît pas car trop petit)

**Screenshots**
![79234969_637601979978342_2669618604516835328_n](https://user-images.githubusercontent.com/45964096/69900967-d349fa00-137a-11ea-8a95-db6b4d255281.png)

**Divers**
On peut régler le problème en mettant le sprite en multiple et en le découpant dans le sprite editor.

**Comment by MightyPietro** [comment]
Lorsque vous importez une image et que vous voulez en faire un sprite ou un élement d'UI : 

- Dans les import settings : selectionnez " Mesh Type " et changez le type de **" Tight "** en **" Full Rect "**

- N'oubliez pas d'Apply !

![image](https://user-images.githubusercontent.com/44057989/70626009-e3d45d00-1c23-11ea-90de-262e3e51fc96.png)
