### ISSUE TITLE
[BUG] - Importation assets

### ISSUE THREAD

**Issue by MargauxLukas** [Narudgi/RubikarioWare#4]
**Description du bug**
Lorsque l'on importe des assets dans le projet, ils sont réduits à un pixel, ce qui rend impossible l'importation d'assets à une taille précise ou même d'assets en général (ex : une fiole bleue sera réduite à un carré bleu d'un pixel)

**Reproduction du bug**
Étapes pour reproduire le problème:
1. Drag & Drop (ou importe avec clic droit) un asset
2. Glisse le dans la scène
3. Le game object créé a bien la taille souhaitée mais le sprite est réduit à un pixel au centre.
4. Voilà

**Comportment attendu**
J'attendais que le sprite s'importe correctement 

**Screenshots**
L'image de base et le résultat sur la scène (je précise que j'ai exactement tout les mêmes réglages que sur un autre projet où cela fonctionne normalement)
![Capture](https://user-images.githubusercontent.com/45992877/69956188-9eb37b00-14ff-11ea-87fc-e5ab4f396447.PNG)
![images](https://user-images.githubusercontent.com/45992877/69956202-a410c580-14ff-11ea-860c-f36babe728be.jpg)

**Comment by MightyPietro** [comment]
Lorsque vous importez une image et que vous voulez en faire un sprite ou un élement d'UI : 

- Dans les import settings : selectionnez " Mesh Type " et changez le type de **" Tight "** en **" Full Rect "**

- N'oubliez pas d'Apply !

![image](https://user-images.githubusercontent.com/44057989/70626009-e3d45d00-1c23-11ea-90de-262e3e51fc96.png)
