### ISSUE TITLE
[BUG] - Impossible de créer un MicroMonoBehavior

### ISSUE THREAD

**Issue by MargauxLukas** [Narudgi/RubikarioWare#5]
**Description du bug**
On ne peut pas créer de scripts MicroMonoBehavior.

**Reproduction du bug**
Étapes pour reproduire le problème:
1. Dans le tab "project", clic droit > create > C# Custom > C# MicroGame
2. Ouvrir avec Visual Studio
3. Le script est un mono behavior de base 

**Comportment attendu**
Créer un MicroMonoBehavior

**Screenshots**
![Capture](https://user-images.githubusercontent.com/45992877/69956618-c0f9c880-1500-11ea-8f95-28e37d610954.PNG)

**Comment by Narudgi** [comment]
Prêt pour la prochaine mise à jour.
