### ISSUE TITLE
[BUG] - Fonction GetRemainingTime() problème de nom

### ISSUE THREAD

**Issue by MargauxLukas** [Narudgi/RubikarioWare#7]
**Description du bug**
La fonction nommée GetRemainingTime() dans le doc d'intégration n'a pas le bon nom et ne s'appelle d'ailleurs pas comme une méthode. 
Il ne faut pas écrire _Macro.GetRemainingTime()_ mais bien _Macro.RemainingTime_
![Capture](https://user-images.githubusercontent.com/45992877/70535278-0fd8db00-1b5d-11ea-9d84-ac5a5cb49d63.PNG)

**Comment by Narudgi** [comment]
Merci du retour, on s'en occupe dès que possible !

**Comment by MargauxLukas** [comment]
D'ailleurs le nom porte à confusion puisqu'il compte (pour un jeu de 5sec) de 0 à 5 et non pas de 5 à 0. Cest donc pas le temps restant mais bien le temps déjà passé.

**Comment by Narudgi** [comment]
Yes, bah faudra soit qu'on inverse le timer, soit changer le nom

**Comment by Narudgi** [comment]
Ok, pour la prochaine mise à jour c'est bon, la doc va être changé, et c'est maintenant RemainingTime le vrai, et le timer est inversé
