### ISSUE TITLE
[FEATURE] - Récupérer la valeur du timer en bpm

### ISSUE THREAD

**Issue by 4erios** [Narudgi/RubikarioWare#9]
On ne peut actuellement récupérer la valeur du timer que en secondes, ce qui peut poser problème pour certains mini-jeu possédant des events timés sur un certain beat.

**Comment by Narudgi** [comment]
Ok, pour la prochaine version j'ai ajouté Remaining Beat en property, ça utilise juste AffectTimeByBPM
